# Generated by Django 2.1 on 2024-01-18 00:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 0, 4, 6, 145137, tzinfo=utc)),
        ),
    ]
